export const DEFINICOES_CONQUISTAS = [
    {
        id: 'primeira_vitoria',
        emoji: '🏆',
        nome: 'Nasce uma Lenda',
        descricao: 'Venceu a partida pela primeira vez.',
        verificar: (s, c) => s.vitorias === 1,
    },
    {
        id: 'cliente_vip',
        emoji: '🤠',
        nome: 'Cliente VIP',
        descricao: 'Jogou 20 partidas completas.',
        verificar: (s, c) => s.partidas >= 20,
    },
    {
        id: 'vitoria_10',
        emoji: '💀',
        nome: 'O Terror da Mesa',
        descricao: 'Ganhou 10 partidas.',
        verificar: (s, c) => s.vitorias >= 10,
    },
    {
        id: 'morte_10',
        emoji: '🤕',
        nome: 'Alvo Fácil',
        descricao: 'Morreu 10 vezes.',
        verificar: (s, c) => s.acertos >= 10,
    },
    {
        id: 'morte_5_6',
        emoji: '😨',
        nome: 'Último Suspiro',
        descricao: 'Ficou faltando só um disparo (5/6).',
        verificar: (s, c) => c.esquivouUltimoTiroAntes,
    },
    {
        id: 'massacre_3_mortes',
        emoji: '🩸',
        nome: 'Banho de Sangue',
        descricao: '3 ou mais morreram num massacre.',
        verificar: (s, c) => c.ehMassacre && c.mortesMassacre >= 3,
    },
    {
        id: 'sorte_caos',
        emoji: '🍀',
        nome: 'Sorte no Caos',
        descricao: 'Faltando dois disparos para morrer acertou outro jogador.',
        verificar: (s, c) => c.sorteCaosAcerto,
    },
    {
        id: 'dose_vinganca',
        emoji: '🤠',
        nome: 'Duplamente Vingativo',
        descricao: 'Eliminou o alvo no modo Dose Dupla.',
        verificar: (s, c) => c.mortosEmDose,
    },
    {
        id: 'dose_sorte',
        emoji: '🎲',
        nome: 'Testando a Sorte',
        descricao: 'Atirou em si mesmo no Dose Dupla e sobreviveu.',
        verificar: (s, c) => c.atirouEmSiDose,
    },
    {
        id: 'dose_intrepido',
        emoji: '🦁',
        nome: 'Não Teme a Morte',
        descricao: 'Atirou em si mesmo 3 vezes na mesma rodada.',
        verificar: (s, c) => c.contadorTirosSiMesmo >= 3,
    },
    {
        id: 'dose_odiado',
        emoji: '🎯',
        nome: 'Odiado',
        descricao:
            'Recebeu 2 tiros seguidos no Dose Dupla e sobreviveu ao primeiro.',
        verificar: (s, c) => c.sobreviveuPrimeiraDose,
    },
    {
        id: 'morte_1_6',
        emoji: '⏱️',
        nome: 'Speedrun do Além',
        descricao: 'Morreu no primeiro disparo.',
        ehOculta: true,
        verificar: (s, c) => c.morreuNoTiro === 1,
    },
    {
        id: 'vidas_gato',
        emoji: '🐈',
        nome: 'Sete Vidas',
        descricao: 'Acumulou 70 sobrevivências.',
        ehOculta: true,
        verificar: (s, c) => s.esquivas >= 70,
    },
    {
        id: 'vitoria_ultimo_tiro',
        emoji: '😎',
        nome: 'Um pé na cova',
        descricao: 'Venceu por um triz (5/6).',
        ehOculta: true,
        verificar: (s, c) => c.venceuUltimoTiroAntes && s.vitorias >= 1,
    },
    {
        id: 'sequencia_vitorias_3',
        emoji: '🔥',
        nome: 'Imorrível',
        descricao: 'Ganhou 3 partidas seguidas.',
        ehOculta: true,
        verificar: (s, c) => s._meta.sequenciaVitorias >= 3,
    },
    {
        id: 'vitoria_sem_tiro',
        emoji: '🤖',
        nome: 'Tá de Hack',
        descricao: 'Venceu sem disparar (0/6).',
        ehOculta: true,
        verificar: (s, c) =>
            s.vitorias >= 1 && s.esquivas === 0 && s.acertos === 0,
    },
    {
        id: 'intangivel',
        emoji: '⚖️',
        nome: 'O Intocável',
        descricao: 'Ganhou tendo sido protegido na rodada final.',
        ehOculta: true,
        verificar: (s, c) => c.foiProtegidoVencedor,
    },
    {
        id: 'rei_mesa',
        emoji: '👑',
        nome: 'Rei da Mesa',
        descricao: 'Ganhou 20 ou mais partidas.',
        ehOculta: true,
        verificar: (s, c) => s.vitorias >= 20,
    },
    {
        id: 'lenda_lendas',
        emoji: '🧙‍♂️',
        nome: 'Lenda das Lendas',
        descricao: 'Ganhou 50 ou mais partidas.',
        ehOculta: true,
        verificar: (s, c) => s.vitorias >= 50,
    },
    {
        id: 'sonhando_alem',
        emoji: '😭',
        nome: 'Estão Deixando a Gente Sonhar... No Além',
        descricao: 'Primeiro a morrer três vezes seguidas.',
        ehOculta: true,
        verificar: (s, c) => s._meta.sequenciaMortes >= 3,
    },
    {
        id: 'morte_teimoso',
        emoji: '☠️',
        nome: 'Morreu de Teimoso',
        descricao: 'Morreu na última bala (6/6).',
        ehOculta: true,
        verificar: (s, c) => c.morreuNoTiro === 6,
    },
    {
        id: 'morte_50',
        emoji: '😭',
        nome: 'Não estou suportando mais',
        descricao: 'Morreu 50 ou mais vezes.',
        ehOculta: true,
        verificar: (s, c) => s.acertos >= 50,
    },
    {
        id: 'morte_100',
        emoji: '🪦',
        nome: 'Veterano do Além',
        descricao: 'Morreu 100 ou mais vezes.',
        ehOculta: true,
        verificar: (s, c) => s.acertos >= 100,
    },
    {
        id: 'santo_estagiario',
        emoji: '😇',
        nome: 'O Santo era Estagiário',
        descricao: 'Morreu na segunda bala (2/6).',
        ehOculta: true,
        verificar: (s, c) => c.morreuNoTiro === 2,
    },
    {
        id: 'inimigo_publico',
        emoji: '🎯',
        nome: 'Inimigo Público nº 1',
        descricao: 'Sobreviveu ao Caos sendo alvo de 3 ou mais jogadores.',
        ehOculta: true,
        verificar: (s, c) => c.inimigoPublicoSobreviveu,
    },
    {
        id: 'ouvinte_diabo',
        emoji: '😈',
        nome: 'Deu ouvido ao mau',
        descricao: 'Atirou em quem o Diabo mandou.',
        verificar: (s, c) => c.ouviuDiabo,
    },
    {
        id: 'esperanca_ultima',
        emoji: '📉',
        nome: 'A Esperança é a última que morre... Você não.',
        descricao: 'Sobreviveu ao caos na 5/6, mas morreu logo em seguida.',
        ehOculta: true,
        verificar: (s, c) => c.esperancaUltimaMorre,
    },
    {
        id: 'zumbi_bar',
        emoji: '🧟',
        nome: 'Zumbi do Bar',
        descricao: 'Jogou 50 ou mais, mas ganhou menos de 5.',
        ehOculta: true,
        verificar: (s, c) => s.partidas >= 50 && s.vitorias < 5,
    },
    {
        id: 'eu_voce',
        emoji: '💞',
        nome: 'Agora sou eu e você meu gostoso!',
        descricao: 'Quando os dois se miram e morrem.',
        ehOculta: true,
        verificar: (s, c) => c.morteCaosMutua,
    },
];
