import { Armazenamento } from './storage.js';

const configuracaoSalva = Armazenamento.obter('configuracao', {
    massacre: false,
    caos: false,
    doseDupla: false,
    trapaceiro: false,
    devMode: false,
    devDireto: false,
});

export const ESTADO = {
    slots: Armazenamento.obter('slots', Array(7).fill(null)),
    bd: Armazenamento.obter('bd', []),
    estatisticas: Armazenamento.obter('estatisticas', {}),
    conquistadas: Armazenamento.obter('conquistadas', {}),
    devMode: configuracaoSalva.devMode || false,
    devDireto: configuracaoSalva.devDireto || false,
    jogo: {
        ativo: false,
        jogadores: [],
        indiceVez: 0,
        cartaMesa: 'A',
        turnosMesa: 0,
        mesasCompletadas: 0,
        narrador: null,
        atirando: false,
        botoesBloqueados: false,
        ehMassacre: false,
        mostrandoTransformacaoMassacre: false,
        indiceProtegido: null,
        ultimoIndiceProtegido: null,
        desbloqueiosRodada: [],
        baralhoFrasesMorte: [],
        indiceFraseMorte: 0,
        trapaceiroNaMira: false,
        fraseTrapaceiroUsada: false,
        travamentoAtivado: false,
        modoMassacre: configuracaoSalva.massacre,
        modoCaos: configuracaoSalva.caos,
        modoDoseDupla: configuracaoSalva.doseDupla,
        modoTrapaceiro: configuracaoSalva.trapaceiro,
        modosAtivos: [],
        revelacaoPapel: {
            ativo: false,
            indiceAtual: 0,
            virado: false,
            podeInteragir: true,
        },
        vinganca: {
            ativo: false,
            indiceVingador: null,
        },
        caos: {
            ativo: false,
            fila: [],
            indiceEscolhaAtual: 0,
            alvos: {},
            votos: {},
            alvoDiabo: null,
            ricocheteuUsado: false,
            mostrandoAlivio: false,
        },
        doseDupla: {
            ativo: false,
            indiceJusticeiro: null,
            tirosRestantes: 2,
            contadorTirosSiMesmo: 0,
        },
        papeis: [],
        trapaceiros: [],
        protecaoComparsaUsada: {},
        historicoMesa: {
            piada: false,
            pare: false,
            reverso: false,
            morteComparsa: false,
            paciencia: false,
            ultimaChance: false,
            ricochete: false,
            trapaceiroRevelado: null,
            vitimaRicochete: null,
        },
        cluesAnteriores: [],
        emFalaDetetive: false,
    },
};
